# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b97ead69c107e352214755a47c5c557"
name = "RCS360 Connect"
handle = "rcs360-connect"
application_url = "https://brad-conclude-educational-generous.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "e-comm-dashboard.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_product_listings,read_customers,write_customers,read_orders,write_orders,read_checkouts,write_checkouts"

[auth]
redirect_urls = [
  "https://brad-conclude-educational-generous.trycloudflare.com/auth/callback",
  "https://brad-conclude-educational-generous.trycloudflare.com/auth/shopify/callback",
  "https://brad-conclude-educational-generous.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
